name: HardCoreWorlds
main: com.Cayviel.HardCoreWorlds.HardCoreWorlds
version: 1.5.0a
commands:
  hcw:
    description: Allows the creation of and removal of a ban from a player, and the manipulation of the ban's duration.
    usage: /<command> <command_option> <player> [world] [duration]