name: HardCoreWorlds
main: com.Cayviel.HardCoreWorlds.HardCoreWorlds
version: 1.1.2.5
commands:
  hcw:
    description: Allows the creation of and removal of a ban from a player, and the manipulation of the ban's duration.
    usage: /<command> <ban_option> <player> [world] [duration]